Update Json for states machines
PenteractStudios/Penteract pull request #13
Opened 2021-05-29 20:38 UTC by JoanMarcBardes

2021-05-29 20:40 UTC, saulzini submitted a review, later dismissed

2021-05-29 21:08 UTC, jcarlos0305 approved these changes

2021-05-30 09:38 UTC, isaacfdez submitted a review, later dismissed

2021-05-30 09:41 UTC, Jordi-Gil requested changes
Blocked until having a new release

2021-05-31 20:42 UTC, isaacfdez approved these changes

2021-06-01 11:52 UTC, jcarlos0305 submitted a review, later dismissed

2021-06-05 15:36 UTC, merged