Feature/cu p3augp upgrades
PenteractStudios/Penteract pull request #159
Opened 2021-07-30 12:13 UTC by Mefiso

Upgrade system finished and skills upgrades implemented. Since Alvaro's singleton class isn't merged, I've had to do a workaround using static members in order to be able to upgrade the corresponding skill depending on the level. 

Furthermore, I encountered a bug that causes a malfunctioning of the Dash upgrade. It is due to the fact that "Active" parameter on Component Colliders is not correctly saved and loaded. This needs to be fixed in the Engine.

Things left to do regarding the upgrades:

- Change color of the rebounded enemy bullets.
- Create Upgrades activation menu on Start Scene.
- Create Debug option to instantly activate an upgrade.

2021-07-30 12:13 UTC, jcarlos0305 commented
Task linked: [CU-p3augp Implement Upgrades mechanic](https://app.clickup.com/t/p3augp)

2021-08-06 20:51 UTC, Jordi-Gil approved these changes

2021-08-06 22:45 UTC, devildrake commented on Penteract/Assets/Scripts/PlayerController.cpp
> +		// TODO: Check whether in level1 or level2
Remove TODO because what the comment says is done right below

2021-08-06 22:47 UTC, devildrake commented on Penteract/Assets/Scripts/SceneTransition.cpp
> +		MEMBER(MemberType::FLOAT, speedTransition),
Identation (Ignore me if you want)

2021-08-06 22:48 UTC, devildrake approved these changes

2021-08-06 22:55 UTC, devildrake requested changes
Reloading scene by losing after getting upgrades appears to bug the upgrade system?

2021-08-06 22:59 UTC, Jordi-Gil commented
Probably the Win/Lose scene is redirecting you to Level1.scene not Level1-Upgrades.scene. Tomorrow, if @Mefiso cannot set up the Level1, I will.

2021-08-07 02:47 UTC, Yonimevicio commented on Penteract/Assets/Scripts/Fang.cpp
> +		if (hasDashed) trailDelay();
I thought you would put it in capital letters, in my version it is already set, you're welcome ;)

2021-08-07 02:47 UTC, Yonimevicio submitted a review, later dismissed

2021-08-07 08:55 UTC, isaacfdez approved these changes

2021-08-07 22:10 UTC, Jordi-Gil approved these changes

2021-08-07 23:14 UTC, Yonimevicio approved these changes

2021-08-08 06:31 UTC, devildrake approved these changes

2021-08-08 08:43 UTC, merged