Feature/cu p3d3rd onimaru ultimate improvements
PenteractStudios/Penteract pull request #164
Opened 2021-08-06 16:28 UTC by devildrake

Enabled movement during ultimate 
Established special movement animation during ultimate if player moves
Bullet spread and size can be set from scene (Tested values that seem to work fine are 0.2 on the radius for the spread and 80 on the start size.

2021-08-06 16:28 UTC, jcarlos0305 commented
Task linked: [CU-p3d3rd Onimaru Ultimate improvement](https://app.clickup.com/t/p3d3rd)

2021-08-09 16:53 UTC, Jordi-Gil approved these changes

2021-08-09 20:20 UTC, magalenyo commented on Penteract/Assets/Scripts/Onimaru.cpp
>  			agent->SetMaxSpeed(movementSpeed);
SetMaxSpeed should be shieldingMaxSpeed, right?

2021-08-09 20:29 UTC, magalenyo requested changes
Compilation errors, from Onimaru.h:
- CanBlast is not correctly declared on the .cpp
- ultimateInUse not declared
- ultimateOn, blastInUse not delcared

![image](https://user-images.githubusercontent.com/27434068/128770130-fe0d95eb-7d48-4c43-a7eb-04cfce66de2b.png)

2021-08-12 21:37 UTC, Jordi-Gil approved these changes

2021-08-18 16:41 UTC, Jordi-Gil approved these changes

2021-08-18 22:59 UTC, magalenyo approved these changes

2021-08-20 11:55 UTC, jcarlos0305 approved these changes

2021-08-20 15:36 UTC, merged