Toggle dialogs in god mode
PenteractStudios/Penteract pull request #268
Opened 2021-09-16 15:46 UTC by jcarlos0305

Moved the god mode to the right side & added the toggle dialogs

2021-09-18 11:49 UTC, Mefiso submitted a review, later dismissed

2021-09-18 14:46 UTC, magalenyo requested changes
- If dialogues are OFF, upgrade orbs disappear.
- You didn't take into account the Stats Displayer when moving the Menu to the right: 
![image](https://user-images.githubusercontent.com/27434068/133892723-5b08f5c8-03e5-4269-a320-f1273865a5b3.png)

- Make the changes in level 2 as well.

2021-09-19 18:42 UTC, jcarlos0305 commented
> * If dialogues are OFF, upgrade orbs disappear.
> * You didn't take into account the Stats Displayer when moving the Menu to the right:
>   ![image](https://user-images.githubusercontent.com/27434068/133892723-5b08f5c8-03e5-4269-a320-f1273865a5b3.png)
> * Make the changes in level 2 as well.

@magalenyo Good catch the stats displayer location, the orbs disappear when toggling dialogs that's expected & also added the changes to the level 2

2021-09-20 21:53 UTC, Jordi-Gil approved these changes

2021-09-21 11:06 UTC, magalenyo approved these changes

2021-09-21 11:17 UTC, Mefiso approved these changes

2021-09-21 13:18 UTC, FrancPS commented
Merging conflicts will appear with #271 in level1.scene.
Let it be merged first since its more complex, and edit the position after with this PR

2021-09-21 15:51 UTC, merged