Improved shield an Onimaru-melee interaction
PenteractStudios/Penteract pull request #269
Opened 2021-09-16 17:34 UTC by Mefiso

In order to see all the changes in action, you'll need to modify the levels by adding the "Impenetrable" game object to Onimaru (you'll find that object inside the new player prefab, inside Onimaru)

2021-09-16 17:34 UTC, jcarlos0305 commented
Task linked: [CU-1eqqv7u Shield should block melee movement](https://app.clickup.com/t/1eqqv7u)

2021-09-19 12:24 UTC, Jordi-Gil requested changes
I set the Impenetrable object inside Onimaru but once you activate the shield, the enemies remain walking around you all the time. Don't know if I'm setting the player in a wrong way.

![38ad44c159867860e1d421668c91e72b](https://user-images.githubusercontent.com/24542154/133927317-ecd2d833-6a20-4842-8a10-fece8ce31d11.gif)

![image](https://user-images.githubusercontent.com/24542154/133927354-ad86cbe1-14f8-4b6d-8028-84de1d2a366a.png)

2021-09-19 17:29 UTC, Mefiso commented
> 
> 
> I set the Impenetrable object inside Onimaru but once you activate the shield, the enemies remain walking around you all the time. Don't know if I'm setting the player in a wrong way.
> 
> ![38ad44c159867860e1d421668c91e72b](https://user-images.githubusercontent.com/24542154/133927317-ecd2d833-6a20-4842-8a10-fece8ce31d11.gif)
> 
> ![image](https://user-images.githubusercontent.com/24542154/133927354-ad86cbe1-14f8-4b6d-8028-84de1d2a366a.png)

Hmm I'll look into it.

2021-09-19 21:55 UTC, Jordi-Gil approved these changes

2021-09-20 11:48 UTC, FrancPS approved these changes

2021-09-21 11:16 UTC, magalenyo approved these changes

2021-09-21 11:17 UTC, merged