OnimaruShoot
PenteractStudios/Penteract pull request #27
Opened 2021-06-02 21:54 UTC by telmiuse

OnimaruBullet Script
TrailScreep update
OnimaruBullet Prefab
OnimaruBullet texture
UpdateSceneNavigation 

Task https://sharing.clickup.com/t/h/kd4rj3/S1FUR2F3M759TSY

2021-06-02 21:54 UTC, jcarlos0305 commented
Task linked: [CU-kd4rj3 Onimaru Shoot Blanace](https://app.clickup.com/t/kd4rj3)

2021-06-03 21:33 UTC, Yonimevicio approved these changes

2021-06-04 11:45 UTC, jcarlos0305 approved these changes

2021-06-04 22:58 UTC, Jordi-Gil submitted a review, later dismissed

2021-06-07 13:15 UTC, Jordi-Gil approved these changes

2021-06-07 23:37 UTC, Yonimevicio submitted a review, later dismissed

2021-06-08 08:23 UTC, telmiuse commented
@Jordi-Gil i cant merge couse we have a problem with stretch, @lowysole is looking for the issue.

2021-06-08 08:29 UTC, lowysole commented
> @Jordi-Gil i cant merge couse we have a problem with stretch, @lowysole is looking for the issue.

The fix will be on an Engine basis, you can continue with this PR, as the implementation seems correct

2021-06-08 08:41 UTC, lowysole commented
> @lowysole i prefer to test it on my branch and then merge once u push the fix. Couse i need to check the script to solve the first frame of the bullet.

Gotcha

2021-06-08 14:02 UTC, Jordi-Gil requested changes

2021-06-09 14:35 UTC, jcarlos0305 submitted a review, later dismissed

2021-06-09 17:13 UTC, Jordi-Gil approved these changes

2021-06-09 17:13 UTC, Jordi-Gil commented on Penteract/Assets/Scripts/PlayerController.cpp
> +					onimaruBulletcript->SetOnimaruDirection(onimaruGunTransform->GetGlobalRotation());
Check nullity, in case bullet has not an OnimaruBullet script, this line will crash.

2021-06-09 17:15 UTC, jcarlos0305 approved these changes

2021-06-09 17:41 UTC, Yonimevicio approved these changes

2021-06-09 17:44 UTC, merged