Assets cleanup
PenteractStudios/Penteract pull request #270
Opened 2021-09-20 09:56 UTC by FrancPS

Some UI had deprecated image textures, so the 3 scenes had been modified. This will conflict with commit

Prefabs and Materials folders might be cleaned further.

2021-09-20 14:21 UTC, Jordi-Gil approved these changes

2021-09-21 11:55 UTC, isaacfdez approved these changes

2021-09-22 16:10 UTC, isaacfdez submitted a review, later dismissed

2021-09-22 16:50 UTC, magalenyo requested changes
Glitch effect and fade out from black when on StartScene broke. Please, review the bug introduced in this PR. Check in with @devildrake or @Jordi-Gil , and if they are not available, I may take a look on thursday.

![image](https://user-images.githubusercontent.com/27434068/134387115-54a57824-bb0a-4460-80f0-dc9425a1d7d8.png)

2021-09-22 20:35 UTC, magalenyo approved these changes

2021-09-23 19:05 UTC, devildrake approved these changes

2021-09-25 12:53 UTC, isaacfdez approved these changes

2021-09-25 15:06 UTC, merged