Hotfix/fang tutorial
PenteractStudios/Penteract pull request #271
Opened 2021-09-21 09:38 UTC by FrancPS

To merge this to level 1:

- Adjust GameController->Dialogue Manager script cameras
  - zoomedCameraPosition (-2,10,6)
  - twoPersonCameraPosition (3,10,6)
- Import the GamePlayScenes object as a prefab, and reassign references
- Edit Fang and Oni tutorial texts (E->Q & "(Hold) Shoot")

Duke is a placeholder in this scene. The final duke prefab or a part of it should be used instead to be congruent with the other duke instances in the game.

2021-09-21 09:39 UTC, jcarlos0305 commented
Task linked: [CU-1ej8fr6 Add Fang Tutorial](https://app.clickup.com/t/1ej8fr6)

2021-09-22 16:41 UTC, isaacfdez submitted a review, later dismissed

2021-09-23 08:42 UTC, Jordi-Gil approved these changes
The key to continue the dialogues is SPACE, but in the image still showing F

2021-09-23 09:11 UTC, FrancPS commented on Penteract/Assets/Scripts/DialogueManager.cpp
>  	dialoguesArray[18] = Dialogue(DialogueWindow::FANG, true, "Onimaru,\nget the repair bots\nready...\nI'm gonna need a break.", &dialoguesArray[19]);
It's not a problem

2021-09-23 09:38 UTC, FrancPS commented
> 
> 
> The key to continue the dialogues is SPACE, but in the image still showing F

This will be edited when the feature is passed to level1.scene

2021-09-25 12:52 UTC, isaacfdez submitted a review, later dismissed

2021-09-26 10:11 UTC, magalenyo requested changes
When pressing Reload Scene on the Main Menu, after video plays, can't perform any action and no Dialogue appears until you open and close the menu. This is probably due to Pause's stop time behavior. This also happens when comming from the StartScene.

2021-09-26 10:30 UTC, Jordi-Gil commented
> When pressing Reload Scene on the Main Menu, after video plays, can't perform any action and no Dialogue appears until you open and close the menu. This is probably due to Pause's stop time behavior. This also happens when comming from the StartScene.

When comming from the StartScene, is probably loading the Level1.scene not the Level1-Tutorial.scene

2021-09-26 11:48 UTC, Jordi-Gil requested changes
When you are in a dialogue and the game is stopped, and you press the ESC button to open the pause menu. Once you return to the game, you can move it with the dialogues actives.

![92e1e15c207b925f44c9e688cdad480c](https://user-images.githubusercontent.com/24542154/134806371-dfa5480a-d1d8-4046-bdc8-9eb3fc10226c.gif)

2021-09-27 09:00 UTC, FrancPS commented
> 
> 
> When pressing Reload Scene on the Main Menu, after video plays, can't perform any action and no Dialogue appears until you open and close the menu. This is probably due to Pause's stop time behavior. This also happens when comming from the StartScene.

Checked. It works fine when the reload and start scene load Level1-Tutorial.scene instead of Level1.scene.

2021-09-27 09:03 UTC, FrancPS commented
> 
> 
> When you are in a dialogue and the game is stopped, and you press the ESC button to open the pause menu. Once you return to the game, you can move it with the dialogues actives.

Fixed

2021-09-28 07:49 UTC, FrancPS commented
I'm including CU-1f91bf7 in this PR. Hold for reviews.

2021-09-30 11:00 UTC, closed without merging