Feature/cu 1eqzn4a explosive barrels throw
PenteractStudios/Penteract pull request #283
Opened 2021-09-26 20:32 UTC by JoanMarcBardes

2021-09-26 20:32 UTC, jcarlos0305 commented
Task linked: [CU-1eqzn4a Explosive barrels throw](https://app.clickup.com/t/1eqzn4a)

2021-09-28 09:25 UTC, FrancPS approved these changes

2021-09-28 10:41 UTC, devildrake approved these changes

2021-09-28 16:01 UTC, Mefiso commented on Penteract/Assets/Scripts/AIDuke.cpp
> +				throwBarrelTimer = 5;
You should have a currentBarrelTimer and a BarrelTimer, the BarrelTimer is the value you set from inspector, then you should decrease the currentBarrelTimer. And when it is 0 you set the currentBarrelTimer to BarrelTimer

2021-09-28 16:16 UTC, Mefiso requested changes
Change the hardcoded barrel timer

2021-09-29 09:36 UTC, merged