Feature/cu 1fmhxg2 emp effect
PenteractStudios/Penteract pull request #285
Opened 2021-09-28 14:14 UTC by telmiuse

2021-09-28 14:14 UTC, jcarlos0305 commented
Task linked: [CU-1fmhxg2 EMP Recived Effect](https://app.clickup.com/t/1fmhxg2)

2021-09-28 23:14 UTC, Jordi-Gil requested changes

2021-09-28 23:14 UTC, Jordi-Gil commented on Penteract/Assets/Scripts/AIMeleeGrunt.cpp
> +					particlesEmp->PlayChildParticles();
Check nullity. In the start you check the nullity of the aux local variable, but at this point this pointer could be null

2021-09-28 23:14 UTC, Jordi-Gil commented on Penteract/Assets/Scripts/AIMeleeGrunt.cpp
> +		particlesPush->PlayChildParticles();
Check nullity. In the start you check the nullity of the aux local variable, but at this point this pointer could be null

2021-09-28 23:14 UTC, Jordi-Gil commented on Penteract/Assets/Scripts/RangedAI.cpp
> +		particlesPush->PlayChildParticles();
Check nullity. In the start you check the nullity of the aux local variable, but at this point this pointer could be null

2021-09-28 23:14 UTC, Jordi-Gil commented on Penteract/Assets/Scripts/RangedAI.cpp
> +					particlesEmp->PlayChildParticles();
Check nullity. In the start you check the nullity of the aux local variable, but at this point this pointer could be null

2021-10-01 14:53 UTC, Jordi-Gil approved these changes

2021-10-02 20:37 UTC, Jordi-Gil approved these changes

2021-10-02 20:37 UTC, merged