Throw barrels animations
PenteractStudios/Penteract pull request #303
Opened 2021-10-03 18:17 UTC by JoanMarcBardes

2021-10-03 18:17 UTC, jcarlos0305 commented
Task linked: [CU-1g0119g Throw barrels animations](https://app.clickup.com/t/1g0119g)

2021-10-03 18:17 UTC, jcarlos0305 commented
Task linked: [CU-p1btku Boss mechanics](https://app.clickup.com/t/p1btku)

2021-10-04 18:07 UTC, Mefiso requested changes
A couple of things: 
1. I know it isn't the final effect but please make that the warning effect ("barrel shadow") lasts exactly until the barrel explodes or reaches the floor, as you prefer, not more. Do it by scripting (set the warning effect duration equal to the timerToDestroy or the falling time).
2. In the condition to check if the barrel has reached the floor, use the parentTransform barrelMesh's transform (changing the threshold accodingly). In the "else" statement force the global position of the parentTransform to be exactly that of the new threshold.

2021-10-06 00:17 UTC, Mefiso commented on Penteract/Assets/Scripts/Barrel.cpp
> +	barrelShadow = barrel->GetParent()->GetParent()->GetChild("BarrelShadowWarning");
Why is this not inside "if(!onFloor)"

2021-10-06 00:26 UTC, Mefiso commented on Penteract/Assets/Scripts/Barrel.cpp
>  			parentTransform->SetGlobalPosition(barrelPos);
PLEASE, on the else enforce that the y component of the global position is EXACTLY the threshold (2.f). If not, in some computer the black mark won't be seen on the floor

2021-10-06 00:33 UTC, Mefiso approved these changes

2021-10-06 14:05 UTC, isaacfdez approved these changes

2021-10-06 17:33 UTC, jcarlos0305 approved these changes

2021-10-06 20:44 UTC, devildrake approved these changes

2021-10-06 21:46 UTC, merged