Feature/cu jzagr7 player combat sounds
PenteractStudios/Penteract pull request #44
Opened 2021-06-07 19:30 UTC by isaacfdez

Added combat sounds to the player. The sounds for Shooting and Changing Character are the same for both character right now, but this will change in the future. You can test this changes on the TestAudioScene

2021-06-07 20:10 UTC, jcarlos0305 commented
Task linked: [CU-jzagr7 Add combat sounds - Main Characters](https://app.clickup.com/t/jzagr7)

2021-06-07 23:00 UTC, Jordi-Gil requested changes

2021-06-07 23:00 UTC, Jordi-Gil commented on Penteract/Assets/Scripts/PlayerController.h
> +	ComponentAudioSource* audios[static_cast<int>(AudioType::TOTAL)];
Uninitialized. The values are undefined, not nullptr. This will pass an If statement and crash when use it. Initialize to  = { nullptr };

2021-06-08 09:14 UTC, Jordi-Gil approved these changes

2021-06-08 09:17 UTC, Yonimevicio approved these changes

2021-06-08 10:27 UTC, jcarlos0305 approved these changes

2021-06-08 14:02 UTC, merged