Rework player controller
PenteractStudios/Penteract pull request #70
Opened 2021-06-25 16:52 UTC by Yonimevicio

Still fixing some bugs:
    - guns animations
    - sounds
    - dash
 Still need to finish cleaning playercontroller.h

2021-06-25 16:52 UTC, jcarlos0305 commented
Task linked: [CU-mb5m9k Rework player controller / AI scripts](https://app.clickup.com/t/mb5m9k)

2021-06-25 21:01 UTC, devildrake requested changes
Found bugs:
- HUD ability cooldown effect not playing
- Most sounds not playing
- Shooting doesn't work properly (Maybe attackspeed or animation related issue)
- Onimaru doesn't have animations
- Fang animation on shooting doesn't play properly
- Dash has a wierd feel to it

2021-06-26 12:56 UTC, Yonimevicio commented on Penteract/Assets/Scripts/Player.cpp
> +int Player::GetMouseDirectionState() {
Hmm okay it's a good idea

2021-06-26 12:56 UTC, Yonimevicio commented on Penteract/Assets/Scripts/Player.cpp
> +void Player::Hit(int damage_)
okay

2021-06-26 12:57 UTC, Yonimevicio commented on Penteract/Assets/Scripts/CameraController.h
> +class CameraController : public Script
yes, all camera code will go in this class

2021-06-28 22:19 UTC, Jordi-Gil approved these changes

2021-06-28 23:26 UTC, Yonimevicio commented on Penteract/Assets/Scripts/Player.cpp
> +int Player::GetMouseDirectionState() {
I will change it in another PR when I include the diagonal animations.

2021-06-28 23:57 UTC, jcarlos0305 submitted a review, later dismissed

2021-06-29 16:31 UTC, Jordi-Gil submitted a review, later dismissed

2021-06-30 10:46 UTC, devildrake approved these changes

2021-06-30 11:48 UTC, jcarlos0305 approved these changes

2021-06-30 14:35 UTC, Jordi-Gil approved these changes

2021-06-30 15:06 UTC, merged