Feature/onimaru shield
PenteractStudios/Penteract pull request #88
Opened 2021-07-04 12:19 UTC by XavierMacias

Shield is merged with develop and has its correct mesh and collider. Sound effects and particles are missing.

2021-07-04 12:34 UTC, Jordi-Gil requested changes
Don't push the files inside .vs/

2021-07-04 20:22 UTC, Jordi-Gil submitted a review, later dismissed

2021-07-04 21:11 UTC, devildrake approved these changes

2021-07-05 16:24 UTC, GBMiro approved these changes

2021-07-05 16:47 UTC, Jordi-Gil approved these changes

2021-07-05 16:48 UTC, merged