Blast Ability
PenteractStudios/Penteract pull request #91
Opened 2021-07-04 15:15 UTC by GBMiro

Implemented blast abilitty (BlastScene.scene to test it)

- Ability activates using Q
- Establish OnAnimationSecondaryTrigger on Fang and Onimaru classes
- Added pushback triggers on Melee Grunt
- Modify SpawnOnClick and EnemySpawnPoint scripts to keep track of enemies in the level (detection is done with maths)
- Exposed pushback's velocity and distance in the enemy script

In order to build all necessary dependencies in the scene:

- Add player GO in SpawnPoint script
- Add RightHandBase GO in PlayerController script
- Add player GO in SpawnOnClick script

2021-07-04 15:15 UTC, jcarlos0305 commented
Task linked: [CU-mke4bx Onimaru blast abillity](https://app.clickup.com/t/mke4bx)

2021-07-04 21:13 UTC, Jordi-Gil submitted a review, later dismissed

2021-07-04 21:23 UTC, devildrake approved these changes

2021-07-05 17:10 UTC, jcarlos0305 submitted a review, later dismissed

2021-07-05 18:43 UTC, Jordi-Gil commented
Check in the Onimary.cpp the nullity of shield and shieldGO.

2021-07-05 18:43 UTC, Jordi-Gil requested changes
Check in the Onimary.cpp the nullity of shield and shieldGO.

2021-07-05 19:17 UTC, Jordi-Gil submitted a review, later dismissed

2021-07-05 19:55 UTC, devildrake approved these changes

2021-07-05 20:07 UTC, Jordi-Gil approved these changes

2021-07-05 20:07 UTC, merged